[package]
name = "ns-rules"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
miette = "1.1.0"
walkdir = "2.3.2"
thiserror = "1.0.25"
owo-colors = "2.0.0"
clap = "3.0.0-beta.4"